import type { Skill } from "./types";

/** Curated from resume (Additional Skills) — proficiencies are representative 1–5. */
export const skills: Skill[] = [
  { name: "TypeScript / JavaScript (React)", category: "frontend", proficiency: 5, order: 0 },
  { name: "HTML", category: "frontend", proficiency: 5, order: 0 },
  { name: "Tailwind CSS", category: "frontend", proficiency: 4, order: 0 },
  { name: "Shaka Player", category: "frontend", proficiency: 4, order: 0 },
  { name: "Python", category: "backend", proficiency: 5, order: 0 },
  { name: "FastAPI", category: "backend", proficiency: 5, order: 0 },
  { name: "Django", category: "backend", proficiency: 4, order: 0 },
  { name: "Java / Kotlin (Android)", category: "backend", proficiency: 4, order: 0 },
  { name: "Go", category: "backend", proficiency: 3, order: 0 },
  { name: "C / C++ / C11", category: "backend", proficiency: 4, order: 0 },
  { name: "FFmpeg (HLS / streaming)", category: "backend", proficiency: 4, order: 0 },
  { name: "Firebase", category: "backend", proficiency: 4, order: 0 },
  { name: "Celery", category: "backend", proficiency: 3, order: 0 },
  { name: "PostgreSQL / SQL", category: "database", proficiency: 5, order: 0 },
  { name: "SQLite", category: "database", proficiency: 4, order: 0 },
  { name: "MongoDB", category: "database", proficiency: 3, order: 0 },
  { name: "AWS", category: "cloud", proficiency: 5, order: 0 },
  { name: "Docker", category: "cloud", proficiency: 5, order: 0 },
  { name: "Kubernetes", category: "cloud", proficiency: 3, order: 0 },
  { name: "OpenStack / Ceph", category: "cloud", proficiency: 3, order: 0 },
  { name: "HLS / DASH & AES-128 DRM", category: "cloud", proficiency: 4, order: 0 },
  { name: "Retrieval-Augmented Generation (RAG)", category: "other", proficiency: 4, order: 0 },
  { name: "LangChain / LangGraph", category: "other", proficiency: 3, order: 0 },
  { name: "ML: scikit-learn, LightGBM, ANN/CNN", category: "other", proficiency: 4, order: 0 },
  { name: "Streamlit", category: "other", proficiency: 4, order: 0 },
  { name: "Git", category: "tools", proficiency: 5, order: 0 },
  { name: "Jira", category: "tools", proficiency: 4, order: 0 },
  { name: "Linux (kernel & userspace)", category: "tools", proficiency: 4, order: 0 },
  { name: "SocketCAN / QEMU-KVM", category: "tools", proficiency: 3, order: 0 },
  { name: "Cursor", category: "tools", proficiency: 4, order: 0 },
];
